/**
 * Dev-environment artifacts for a tenant workspace (M1.5 ②, dev-environment.md):
 *   docker-compose.yml   — self-contained dev env (buildingos-runtime + postgres)
 *   .env                 — secrets: MODEL_TOKEN / GIT_TOKEN / PG_PASSWORD (D21)
 *
 * The compose is self-contained — it references the `buildingos-runtime:dev`
 * image by name, NOT a tool-repo path. `buildingos dev` builds that image from
 * the tool repo first (BUILDINGOS_TOOL_DIR), then runs compose up. This keeps
 * the tenant portable: the compose never leaks an absolute tool-repo path and
 * never hard-fails on a missing BUILDINGOS_TOOL_DIR variable.
 */
import { existsSync } from 'node:fs';
import { randomBytes } from 'node:crypto';
import path from 'node:path';

export interface DevEnvSpec {
  /** Absolute path of the tenant workspace (mounted at /workspace). */
  tenantDir: string;
  /** Absolute path of the BuildingOS tool repository (used to build the image); optional. */
  toolDir?: string;
}

const COMPOSE_TEMPLATE = `# BuildingOS dev environment (generated by buildingos init, M1.5 ②)
# cd <tenant> && docker compose up   →  buildingos-runtime (CLI) + postgres
# Secrets come from .env (D21): MODEL_TOKEN / GIT_TOKEN / PG_PASSWORD.
# PG_PORT overrides the host-side postgres port when 5432 is taken.
#
# Self-contained: this compose references the buildingos-runtime:dev image by
# name. Build that image first (once) from the tool repo, or let buildingos dev
# do it automatically:
#   docker build -t buildingos-runtime:dev -f deploy/Dockerfile <tool-repo>
name: buildingos-dev

services:
  buildingos-runtime:
    image: buildingos-runtime:dev
    container_name: buildingos-runtime
    working_dir: /workspace
    # Keep the container alive; work inside it via: docker compose exec buildingos-runtime buildingos <cmd>.
    entrypoint: ['sleep', 'infinity']
    volumes:
      - .:/workspace
    environment:
      - BUILDINGOS_WORKSPACE=/workspace
      - MODEL_TOKEN=\${MODEL_TOKEN:-}
      - GIT_TOKEN=\${GIT_TOKEN:-}
    stdin_open: true
    tty: true
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: buildingos-postgres
    environment:
      POSTGRES_USER: buildingos
      POSTGRES_PASSWORD: \${PG_PASSWORD:?set PG_PASSWORD in .env}
      POSTGRES_DB: buildingos
    ports:
      - '\${PG_PORT:-5432}:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
`;

/** Render the tenant docker-compose.yml (self-contained; image reference, not a tool-repo path). */
export function renderDevCompose(spec: DevEnvSpec): string {
  return COMPOSE_TEMPLATE;
}

/**
 * Compose the tenant .env lines: existing MODEL_TOKEN/GIT_TOKEN plus a fresh
 * PG_PASSWORD (random, never Git, D21). Returns the full .env content.
 */
export function renderDevEnv(modelToken: string, gitToken: string | undefined, pgPassword: string): string {
  const git = gitToken ? `GIT_TOKEN=${gitToken}` : '# GIT_TOKEN (skipped; reuse system credentials)';
  return `MODEL_TOKEN=${modelToken}\n${git}\nPG_PASSWORD=${pgPassword}\n`;
}

/** 24-hex random password for local postgres (crypto.randomBytes). */
export function randomPgPassword(): string {
  return randomBytes(12).toString('hex');
}

/**
 * Locate the BuildingOS tool repository from a start directory by walking up
 * for the tool marker (pnpm-workspace.yaml). Returns undefined when not found
 * (e.g. global installs whose bundle lives in the pnpm store).
 */
export function findToolDir(startDir: string): string | undefined {
  let dir = path.resolve(startDir);
  for (;;) {
    if (existsSync(path.join(dir, 'pnpm-workspace.yaml'))) return dir;
    const parent = path.dirname(dir);
    if (parent === dir) return undefined;
    dir = parent;
  }
}
