/**
 * Codex view rendering (adapter-contract §4 mapping tables).
 * Files: .codex/skills/<name>/SKILL.md (parser.rs consumes name/description/metadata.short-description)
 * + openai.yaml (interface/policy/dependencies; snake_case keys, calibration point C1)
 * + AGENTS.md (rules + persona merged, session-level) + config.toml (D13–D15).
 */
import { stringify as stringifyYaml } from 'yaml';
import type { GeneratedFile, SkillDoc, TenantDocs } from '@buildingos/normalizer';

/** Codex SKILL.md frontmatter — the parser consumes exactly name/description/metadata.short-description. */
function renderSkillFrontmatter(s: SkillDoc): Record<string, unknown> {
  const fm: Record<string, unknown> = { name: s.name, description: s.description };
  const short = typeof s.metadata['short-description'] === 'string' ? s.metadata['short-description'] : s.ui?.shortDescription;
  if (short) fm['metadata'] = { 'short-description': short };
  return fm;
}

/** openai.yaml companion (C1: snake_case keys, re-verified against the adopted version). */
function renderOpenaiYaml(s: SkillDoc, docs: TenantDocs): string {
  const cfg = docs.config;
  const data: Record<string, unknown> = {};
  const ui = s.ui;
  if (ui && Object.keys(ui).some((k) => ui[k as keyof typeof ui])) {
    data['interface'] = {
      ...(ui.displayName ? { display_name: ui.displayName } : {}),
      ...(ui.shortDescription ? { short_description: ui.shortDescription } : {}),
      ...(ui.iconSmall ? { icon_small: ui.iconSmall } : {}),
      ...(ui.iconLarge ? { icon_large: ui.iconLarge } : {}),
      ...(ui.brandColor ? { brand_color: ui.brandColor } : {}),
      ...(ui.defaultPrompt ? { default_prompt: ui.defaultPrompt } : {}),
    };
  }
  data['policy'] = {
    ...(!s.invocation.implicit ? { allow_implicit_invocation: false } : {}),
    ...(s.products.length > 0 ? { products: s.products } : {}),
  };
  if (s.dependencies.length > 0) {
    data['dependencies'] = {
      tools: s.dependencies.map((d) => {
        const reg = cfg.mcpServers.find((m) => m.name === d.value);
        return {
          type: d.type,
          value: d.value,
          ...(reg?.transport ? { transport: reg.transport } : {}),
          ...(reg?.command ? { command: reg.command } : {}),
          ...(reg?.url ? { url: reg.url } : {}),
        };
      }),
    };
  }
  return stringifyYaml(data);
}

function renderSkillFiles(s: SkillDoc, docs: TenantDocs, assets?: (rel: string) => string | undefined): GeneratedFile[] {
  const base = `.codex/skills/${s.name}`;
  const files: GeneratedFile[] = [
    { path: `${base}/SKILL.md`, content: `---\n${stringifyYaml(renderSkillFrontmatter(s))}---\n${s.body}`, kind: 'skill' },
    { path: `${base}/openai.yaml`, content: renderOpenaiYaml(s, docs), kind: 'config' },
  ];
  for (const ref of s.references) {
    const content = assets?.(ref);
    if (content !== undefined) files.push({ path: `${base}/${ref}`, content, kind: 'skill' });
  }
  for (const script of s.scripts) {
    const content = assets?.(script);
    if (content !== undefined) files.push({ path: `${base}/${script}`, content, kind: 'skill' });
  }
  return files;
}

/** AGENTS.md: rules (by order) then the merged persona body (session-level developer instructions, D12). */
function renderAgentsMd(docs: TenantDocs): string {
  const lines: string[] = [];
  const orderedRules = [...docs.rules].filter((r) => r.enabled).sort((a, b) => a.order - b.order);
  const orderedPrompts = [...docs.prompts].filter((p) => p.enabled).sort((a, b) => a.order - b.order);
  for (const r of orderedRules) {
    for (const sec of r.sections) {
      if (sec.heading) lines.push(`# ${sec.heading}`, '', sec.body, '');
    }
  }
  for (const p of orderedPrompts) {
    lines.push(p.body.trim(), '');
  }
  return lines.join('\n').trimEnd() + '\n';
}

/** config.toml (D13–D15): model / sandbox_mode / approval_policy / mcp_servers. */
function renderConfigToml(docs: TenantDocs): string {
  const c = docs.config;
  const lines: string[] = [
    '# Generated by BuildingOS compile() (adapter-contract §4.4 mapping)',
    '',
    ...(c.model ? [`model = "${c.model}"`] : []),
    `sandbox_mode = "${c.sandbox}"`,
    `approval_policy = "${c.approval}"`,
    '',
  ];
  for (const m of c.mcpServers) {
    lines.push(`[mcp_servers.${m.name}]`);
    if (m.command) lines.push(`command = "${m.command}"`);
    if (m.url) lines.push(`url = "${m.url}"`);
    lines.push('');
  }
  return lines.join('\n').trimEnd() + '\n';
}

export function renderCodexView(docs: TenantDocs, assets?: (skill: string, rel: string) => string | undefined): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  for (const s of docs.skills) {
    files.push(...renderSkillFiles(s, docs, (rel) => assets?.(s.name, rel)));
  }
  files.push({ path: '.codex/AGENTS.md', content: renderAgentsMd(docs), kind: 'rule' });
  files.push({ path: '.codex/config.toml', content: renderConfigToml(docs), kind: 'config' });
  return files;
}
