/**
 * Dev environment control (M1.5 ②) — docker compose operations on the tenant
 * workspace. The compose file lives in the workspace (generated by init).
 */
import { spawn } from 'node:child_process';
import { existsSync } from 'node:fs';
import path from 'node:path';

export interface DevStatus {
  workspace: string;
  composeExists: boolean;
  containers: DevContainer[];
  error?: string;
}

export interface DevContainer {
  name: string;
  service: string;
  status: string;
  ports?: string;
}

function hasCompose(workspace: string): boolean {
  return existsSync(path.join(workspace, 'docker-compose.yml'));
}

export async function devStatus(workspace: string): Promise<DevStatus> {
  const base: DevStatus = { workspace, composeExists: hasCompose(workspace), containers: [] };
  if (!base.composeExists) return base;
  try {
    const out = await runDocker(['compose', 'ps', '--format', 'json'], workspace);
    const lines = out.trim().split('\n').filter(Boolean);
    base.containers = lines.map((line) => {
      try {
        const j = JSON.parse(line) as Record<string, unknown>;
        const name = String(j.Name ?? j.name ?? '');
        const service = String(j.Service ?? j.service ?? name.split('-')[0] ?? '');
        const state = String(j.State ?? j.state ?? '');
        const status = String(j.Status ?? j.status ?? state);
        const ports = String(j.Ports ?? j.ports ?? '');
        return { name, service, status, ports };
      } catch {
        return { name: line, service: '', status: '' };
      }
    });
  } catch (err) {
    base.error = err instanceof Error ? err.message : String(err);
  }
  return base;
}

export interface DevActionResult {
  ok: boolean;
  output: string;
  error?: string;
}

function runDocker(args: string[], cwd: string): Promise<string> {
  return new Promise((resolve, reject) => {
    const child = spawn('docker', args, { cwd, env: process.env });
    let out = '';
    let err = '';
    child.stdout.on('data', (d) => (out += String(d)));
    child.stderr.on('data', (d) => (err += String(d)));
    child.on('error', (e) => reject(e));
    child.on('close', (code) => {
      if (code === 0) resolve(out + err);
      else reject(new Error(`docker ${args.join(' ')} exited ${code}: ${err || out}`));
    });
  });
}

export async function devUp(workspace: string, opts?: { detached?: boolean; pgPort?: string }): Promise<DevActionResult> {
  if (!hasCompose(workspace)) {
    return { ok: false, output: '', error: `no docker-compose.yml in ${workspace} — run buildingos init first` };
  }
  const args = ['compose', 'up'];
  if (opts?.detached !== false) args.push('-d');
  const env = { ...process.env };
  if (opts?.pgPort) env.PG_PORT = opts.pgPort;
  try {
    const output = await runDocker(args, workspace);
    return { ok: true, output };
  } catch (err) {
    return { ok: false, output: '', error: err instanceof Error ? err.message : String(err) };
  }
}

export async function devDown(workspace: string, opts?: { volumes?: boolean }): Promise<DevActionResult> {
  if (!hasCompose(workspace)) {
    return { ok: false, output: '', error: `no docker-compose.yml in ${workspace}` };
  }
  const args = ['compose', 'down'];
  if (opts?.volumes) args.push('-v');
  try {
    const output = await runDocker(args, workspace);
    return { ok: true, output };
  } catch (err) {
    return { ok: false, output: '', error: err instanceof Error ? err.message : String(err) };
  }
}
